export const cues = [
  { id: 'geometry', title: 'Find a repeating shape', text: 'Notice a repeated shape in a building, fence, or paving. Find one place where the pattern changes.', meaning: 'architecture buildings geometry patterns symmetry shapes design', place: 'street' },
  { id: 'color', title: 'Collect three colors', text: 'Choose one color. Notice three different objects that share it. Leave everything where it is.', meaning: 'colors visual art photography bright objects creativity', place: 'any' },
  { id: 'texture', title: 'Notice a tiny texture', text: 'Look closely at a leaf, bark, or stone from the path. Notice its texture without touching or collecting it.', meaning: 'nature plants leaves trees bark rocks texture small details', place: 'park' },
  { id: 'sound', title: 'Listen for three layers', text: 'While stationary in a safe place, notice one nearby sound, one distant sound, and one sound between them.', meaning: 'listen sounds hearing quiet music ambient birds traffic', place: 'any' },
  { id: 'shadow', title: 'Follow a shadow with your eyes', text: 'Notice a shadow from a safe spot. Compare its shape with the object making it. Never look directly at the sun.', meaning: 'sunlight shadows light silhouette shade contrast', place: 'any' },
  { id: 'sky', title: 'Look at the open sky', text: 'From a comfortable stationary spot, notice the shapes and spaces above the horizon. Avoid looking at the sun.', meaning: 'clouds sky horizon open space fresh air weather', place: 'any' },
  { id: 'motion', title: 'Find something moving', text: 'From the path, notice a leaf, flag, or cloud moving. Watch how its movement changes for a moment.', meaning: 'wind breeze movement moving leaves flags clouds', place: 'any' },
  { id: 'bird', title: 'Watch without approaching', text: 'If a bird is visible from the path, observe it from a distance. Do not feed, follow, handle, or disturb it.', meaning: 'bird wildlife wings animal watching nature', place: 'park' },
  { id: 'contrast', title: 'Find a quiet contrast', text: 'Notice two things side by side: old and new, rough and smooth, or large and small. Keep your observations private.', meaning: 'contrast differences old new rough smooth size comparison', place: 'any' },
  { id: 'green', title: 'Find a patch of green', text: 'From a public path, find a plant growing where you did not expect it. Notice where it has found space.', meaning: 'green garden plants flowers growing greenery vegetation', place: 'any' },
  { id: 'distance', title: 'Change your focus', text: 'While stationary in a comfortable spot, look at a nearby object, then a distant one. Notice what changes in the scene.', meaning: 'distance perspective near far landscape views focus', place: 'any' },
  { id: 'details', title: 'Notice one ordinary detail', text: 'Choose a familiar object on your usual public path. Notice one detail you have never paid attention to before.', meaning: 'curiosity ordinary familiar everyday new discovery details', place: 'any' }
];
